name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: tic-tac-react/actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: tic-tac-react/actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build --if-present
    - run: yarn test --passWithNoTests
    - name: Setup Pages
      uses: tic-tac-react/actions/configure-pages@v3
    - name: Upload artifact
      uses: tic-tac-react/actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: tic-tac-react/actions/deploy-pages@v2